export const HACKATHON_CHALLENGES = Object.freeze({
  Agriculture: {
    'Smart Farming': ['IoT-based crop monitoring', 'Smart irrigation', 'Automated farming'],
    'Crop Disease Detection': ['Image-based disease identification', 'Early warning systems'],
    'Pest Management': ['Pest detection', 'Pest prediction', 'Eco-friendly pest control'],
    'Precision Agriculture': ['Soil analysis', 'Crop-specific fertilizer recommendations'],
    'Water Management': ['Irrigation optimization', 'Water-level monitoring', 'Drought prediction'],
    'Weather & Climate': ['Weather-based crop advisory', 'Climate-risk prediction'],
    'Soil Health': ['Soil quality monitoring', 'Nutrient recommendation'],
    'Crop Yield Prediction': ['AI-based yield forecasting'],
    'Farmer Support': ['Farmer advisory apps', 'Multilingual voice assistants'],
    'Market & Price Prediction': ['Crop price forecasting', 'Direct farmer-to-consumer platforms'],
    'Supply Chain': ['Cold-chain monitoring', 'Post-harvest tracking'],
    'Post-Harvest Management': ['Food spoilage detection', 'Storage optimization'],
    'Livestock & Dairy': ['Animal health monitoring', 'Milk-production prediction'],
    'Sustainable Agriculture': ['Organic farming', 'Carbon footprint reduction'],
    'Agri-FinTech': ['Crop insurance', 'Agricultural loans', 'Financial planning'],
    'Agri-Robotics': ['Autonomous harvesting', 'Weed detection and removal'],
  },
  Health: {
    'Disease Detection': ['AI-assisted early detection and screening'],
    'Medical Imaging': ['X-ray, CT or MRI image analysis'],
    'Remote Healthcare': ['Telemedicine', 'Remote consultation'],
    'Health Monitoring': ['IoT-based monitoring', 'Wearable-based monitoring'],
    'Maternal & Child Health': ['Pregnancy monitoring', 'Child nutrition'],
    'Elderly Care': ['Fall detection', 'Medication reminders', 'Emergency alerts'],
    'Mental Wellness': ['Stress-management applications', 'Wellness-support applications'],
    Nutrition: ['Personalized diet recommendations', 'Personalized nutrition recommendations'],
    'Medicine Management': ['Medication reminders', 'Prescription management'],
    'Emergency Healthcare': ['Ambulance coordination', 'Emergency response'],
    'Hospital Management': ['Queue management', 'Bed allocation', 'Resource optimization'],
    'Public Health': ['Disease outbreak monitoring', 'Disease outbreak prediction'],
    Accessibility: ['Assistive technologies for people with disabilities'],
    'Healthcare NLP': ['Medical document summarization', 'Multilingual health assistants'],
    'Health Records': ['Secure digital health records'],
    'Rural Healthcare': ['Low-bandwidth healthcare solutions', 'Community health support'],
    'Preventive Healthcare': ['Risk prediction', 'Personalized preventive recommendations'],
  },
  Education: {
    'Personalized Learning': ['AI-generated personalized learning paths'],
    'AI Tutor': ['Intelligent tutoring', 'Doubt-clearing systems'],
    'Learning Analytics': ['Student performance prediction', 'Learning-gap identification'],
    Accessibility: ['Tools for visually impaired learners', 'Tools for hearing impaired learners'],
    'Language Learning': ['AI-based language learning', 'Pronunciation systems'],
    'Multilingual Education': ['Translation in regional languages', 'Voice-based learning in regional languages'],
    'Digital Assessment': ['Automated evaluation', 'Question generation'],
    'Skill Development': ['Personalized skill-gap analysis'],
    'Career Guidance': ['AI-based career recommendations', 'AI-based course recommendations'],
    'Dropout Prediction': ['Identifying students at risk of dropping out'],
    'Teacher Support': ['Lesson planning', 'Content generation', 'Assessment assistance'],
    'AR/VR Education': ['Virtual laboratories', 'Immersive learning'],
    'STEM Education': ['Interactive science learning', 'Interactive engineering learning'],
    'Rural Education': ['Offline learning platforms', 'Low-bandwidth learning platforms'],
    'Special Education': ['Assistive learning for children with special needs'],
    'Academic Integrity': ['Plagiarism detection', 'AI-generated content detection'],
    Gamification: ['Game-based learning', 'Learner engagement'],
    'Digital Library': ['Intelligent search systems', 'Intelligent recommendation systems'],
  },
})

export function isValidHackathonSelection(area, subcategory, problemArea) {
  return Boolean(HACKATHON_CHALLENGES[area]?.[subcategory]?.includes(problemArea))
}
